controller_list:
  - name: fake_arm_kin_chain_controller
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_base_planar_controller
    joints:
      - virtual_base
  - name: fake_base_arm_group_controller
    joints:
      - virtual_base
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5